### ISSUE TITLE
Roadmap to baselax-v0.1.0

### ISSUE THREAD

**Issue by mansicer** [mansicer/baselax#8]
Here are features that baselax plans to support in version 0.1.0:

- [x] Determine the basic agent design and naming conventions: #7 
- [ ] Support on-policy training and off-policy training with `learn` method.
- [ ] Algorithm implementations including DQN, PPO, DDPG.
- [ ] Preliminary experimental results in major Atari and MuJoCo scenarios.
- [ ] Basic documentation of Quick start and several examples.

Some minor improvements:

- [x] #10
- [x] Wrap abstract agent class methods with `@abstractmethod`.

**Comment by liyc-ai** [comment]
Provide `__version__`  metadata, https://github.com/mansicer/baselax/pull/9
